[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "abl.vpath"
dynamic = ["version"]
description = "A OO-abstraction of file-systems"
authors = [
    { name = "The Ableton Web Team", email = "webteam@ableton.com" }
]
urls = { "GitHub" = "https://github.com/AbletonAG/abl.vpath" }
license = { text = "MIT" }
dependencies = [
    "decorator",
    "abl.util",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["abl*"]
exclude = ["tests"]

[project.optional-dependencies]
test = [
    "coverage==7.6.0",
    "pytest==9.0.3",
    "pytest-cov==5.0.0",
    "flake8==7.1.0",
    "flake8_builtins==2.5.0"
]
dev = [
    "pylint",
    "build",
    "ipdb==0.13.13"
]

[project.entry-points."abl.vpath.plugins"]
localfilefs = "abl.vpath.base.localfs:LocalFileSystem"
memoryfs = "abl.vpath.base.memory:MemoryFileSystem"
zipfs = "abl.vpath.base.zip:ZipFileSystem"

[tool.setuptools_scm]
version_file = "abl/vpath/_version.py"
